### ISSUE TITLE
Some thoughts about memcopy

### ISSUE THREAD

**Issue by chrboesch** [ratfactor/zigish#3]
Dave, first of all, great work that let me buy a book  :smile: and got me thinking about this part: `std.mem.copy(u8, &args[i], tok);`. 
I mean, why would it be necessary to copy this chunk of the memory when we already have a pointer to an allocated memory? It should be enough to save this pointer like this: `args[i] = @ptrCast(*align(1) const [255:0]u8, tok.ptr).*;`.
And it actually works as well as thought!

**Comment by ratfactor** [comment]
@chrboesch You're right!  In which case, I no longer need the storage for the copied strings, right?

I feel like I should be able to get rid of my `args` array entirely and just store the token pointers in `args_ptrs`.

```
var args: [max_args][max_arg_size:0]u8 = undefined; // <---- DELETE ME!
```

On paper, this seems so simple (I could definitely do it in assembly!), but I can't figure out how to express it in Zig.

```
var args_ptrs: [max_args:null]?[*:0]u8 = undefined;

// Split by a single space. (tokenize)
// ...

var i: usize = 0;
while (tokens.next()) |tok| {

    // 1. Somehow cast tok.ptr to ?[*:0]u8

    // 2. Write a sentinel 0 after the token (replacing the space in the string)

    i += 1;
}
args_ptrs[i] = null; // add sentinel null
```

Does that logic at least make sense?

Thanks!

Oh, and you won't regret "The Linux Programming Interface" by Michael Kerrisk. Great book. I've referenced it several times since writing that article.

**Comment by chrboesch** [comment]
> I feel like I should be able to get rid of my `args` array entirely and just store the token pointers in `args_ptrs`.

ok

> var args: [max_args][max_arg_size:0]u8 = undefined; // <---- DELETE ME!

ok

> On paper, this seems so simple (I could definitely do it in assembly!), but I can't figure out how to express it in Zig.

:smile: 

> Does that logic at least make sense?

yes, of course

>  // 2. Write a sentinel 0 after the token (replacing the space in the string)

I think this is the challenge (the only one), right? Since 'tok' is a constant, we can't just change the last byte. Therefore, the copy to the array was necessary.

To solve this, I tried 
```
        var i: usize = 0;
        var n: usize = 0;
        var ofs: usize = 0;
        while (i < input_str.len) : (i += 1) {
            if (input_str[i] == 32) {
                input_str[i] = 0;
                args_ptrs[n] = @ptrCast(*align(1) const [*:0]u8, &input_str[ofs]).*;
                n += 1;
                ofs = i + 1;
            }
        }
        input_str[i - 1] = 0;
        args_ptrs[n] = @ptrCast(*align(1) const [*:0]u8, &input_str[ofs]).*;

```
instead of `std.mem.split(..)` but the problem is the same, the input string does not change the space against a null byte. I get a 'sentinel error'. Maybe you have a better idea?

**Comment by chrboesch** [comment]
Addendum: 
> the input string does not change the space against a null byte. 

That is not correct. The byte will be changed, but we can not add a sentinel after the last argument. 
> Does that logic at least make sense?

I'm not shure anymore, but it's too late for me now (midnight is over).

**Comment by chrboesch** [comment]
Progress: One of my mistakes was to change the slice instead of the buffer. Now I do (my input is always 'ls -al'):
```
...
if (input_buffer[i] == 32) {
    input_buffer[i] = 0;
...
```
and then I get `input buf = 6c73002d616c00` and that looks fine. However, when I print out the args I see
```
arg 0 = 6c73202d616c
arg 1 = 2d616c
```
and that's not correct. The args are just pointers to the buffer, and they should look like the buffer. Strange. But I will find out...

**Comment by chrboesch** [comment]
A step further. Now I know the right notation: `const arg = input_buf[i..sent:0];` that gives a valid `[*:0]T` with the right content. :smile:

**Comment by chrboesch** [comment]
```
        var ofs: usize = 0;
        while (i < input_str.len) : (i += 1) {
            if (input_buf[i] == 32) {
                input_buf[i] = 0;
                const arg = input_buf[ofs..i:0]; 
                ofs = i + 1;

....
```
We use the slice just for the lenght of the input bytes. After changing the space into a null-byte, we cast this to a slice with sentinel. That works so far. The last challenge is to cast this into the pointer array.

**Comment by ratfactor** [comment]
Yeah, as I recall, that final cast was what I gave up on when I first tried to do that... oh yeah, this part looks like it:

> (In some of my earlier failed attempts, I tried to go straight from `[N][M:0]u8` to `[*:null][*:0]u8` which proved to be a lot of mental gymnastics, a surprising amount of code, and I never quite got it right.)

http://ratfactor.com/zig/forking-is-cool

I even stumped the folks on the Zig Discord channel who happened to be on when I was attempting it.

Good luck. I hope you can do what I could not so I can update the article after a year and a half. :smile:

**Comment by chrboesch** [comment]
>  I hope you can do what I could not so I can update the article after a year and a half.

You can start sharpening your pencil. :wink:

**Comment by chrboesch** [comment]
When I look at it like this, I think it wasn't that hard. But that's always how it is afterwards. In any case, I learned a lot. And now I hope you like it. :smile:

**Comment by ratfactor** [comment]
I love it! Thank you!

I've updated my article: [ratfactor.com/zig/forking-is-cool](http://ratfactor.com/zig/forking-is-cool)

(You should see a Note at the top "UPDATE" with a link to the new section.)

Let me know if you happen to spot any mistakes. :smile:

**Comment by chrboesch** [comment]
Thank you very much, I think it's great! And I don't find any errors, only Andrew would find them. :wink:
